### ISSUE TITLE
alias BUILD file should actually live in //cargo, not //cargo/vendor

### ISSUE THREAD

**Issue by SirVer** [acmcarther/cargo-raze#29] opened 2018-02-13 17:37 UTC
Right now after the process, you will have your `workspace_path = "//cargo"` directory populated with: 
- Cargo.toml, your source for the `third_party` packages you want to pull in.
- Cargo.lock, the generated log file.
- `vendor` directory, containing output of `vendor -x` and `raze`. 

Building now looks like this: `bazel build //cargo/vendor:log`. I would prefer if it were `//cargo:log`. Possible?

**Comment by acmcarther** [comment] 2018-02-13 18:09
ACK. Yeah, the remote version already does this, but the older vendoring code didn't by design. I was concerned people would want to put things in //cargo, but if we generate a BUILD file users won't be able to add anything else there.

This should be a reasonable change, though @mfarrugi may want to weigh in.

**Comment by mfarrugi** [comment] 2018-02-14 00:26
The vendor suffix has only added noise for us. It bothered me a little, but
not enough to add an alias or workspace wrapper.

**Comment by acmcarther** [comment] 2018-02-17 01:10
Fixed in 0.0.17. Verified in https://github.com/acmcarther/cargo-raze-examples/commit/72e348bbd07e58ed095cad0ad09892cf2ba35bb6

**Closed as completed by acmcarther** 2018-02-17 01:10 UTC
